export interface Product {
  id: string;
  name: string;
  category: string;
  collection: string;
  price: number;
  description: string;
  features: string[];
  dimensions: string;
  material: string;
  finish: string;
  image: string;
  theme: string;
}

export const products: Product[] = [
  {
    id: "1",
    name: "BOTANICAL EMERALD CHESSBOARD",
    category: "Chess",
    collection: "Private Collection",
    price: 150000,
    description: "Curated expression of craftsmanship and rare materials. Each piece is conceived to be timeless, distinctive, and eternally collected.",
    features: ["Handcrafted resin", "Real botanical inclusions", "Weighted pieces", "Certificate of authenticity"],
    dimensions: "60 × 60 × 8 cm",
    material: "Premium Resin & Gold Leaf",
    finish: "High-Gloss Faceted",
    image: "/Emerald and Obsidian Chessboard.png", 
    theme: "Green",
  },
  {
    id: "2",
    name: "SAPPHIRE CRYSTALLINE BASIN",
    category: "Basins",
    collection: "Private Residence",
    price: 220000,
    description: "A singular expression of artistry — sculpted in premium resin and finished by hand to transform every interior into a statement of refinement.",
    features: ["Deep blue sapphire hue", "Faceted crystalline exterior", "Smooth interior bowl", "Gold-plated drain cover"],
    dimensions: "Ø 45 × 15 cm",
    material: "Premium Resin",
    finish: "High-Gloss Faceted",
    image: "/Sink  Blue and Gold.png",
    theme: "Blue Gold",
  },
  {
    id: "3",
    name: "HERITAGE CAR TABLE",
    category: "Tables",
    collection: "Collector's Suite",
    price: 350000,
    description: "An extraordinary centrepiece embedding miniature heritage cars in crystal-clear resin, supported by a polished gold framework.",
    features: ["Embedded vintage models", "Gold-plated stainless steel base", "Scratch-resistant surface", "Unique serial number"],
    dimensions: "Ø 90 × 45 cm",
    material: "Resin & Stainless Steel",
    finish: "Crystal Clear Polish",
    image: "/Luxury Model Car Showcase Table.png",
    theme: "Black Premium",
  },
  {
    id: "4",
    name: "CELESTIAL WALL CLOCK",
    category: "Wall Art",
    collection: "Private Collection",
    price: 180000,
    description: "A mesmerizing timepiece featuring deep lapis lazuli pigments and gold leaf, resembling a galaxy suspended in time.",
    features: ["Silent sweeping movement", "Gold leaf detailing", "Organic edge design", "Wall mounting hardware included"],
    dimensions: "80 × 60 × 7 cm",
    material: "Resin & Gold Leaf",
    finish: "Textured & Gloss",
    image: "/Sapphire Geode Crystal Wall Clock.png",
    theme: "Blue Gold",
  },
  {
    id: "5",
    name: "BLUSH CRYSTALLINE BASIN",
    category: "Basins",
    collection: "Private Residence",
    price: 220000,
    description: "Soft, elegant, and timeless. The blush crystalline basin brings a warm, opulent glow to bespoke bathroom spaces.",
    features: ["Soft pink hue", "Faceted crystalline exterior", "Smooth interior bowl", "Gold-plated drain cover"],
    dimensions: "Ø 45 × 15 cm",
    material: "Premium Resin",
    finish: "High-Gloss Faceted",
    image: "/Pink Crystal Basin on Black Marble.png",
    theme: "Pink White",
  },
  {
    id: "6",
    name: "OBSIDIAN GOLD TABLE",
    category: "Tables",
    collection: "Private Collection",
    price: 280000,
    description: "Bold, dramatic, and opulent. Deep black resin fractured with striking veins of gold.",
    features: ["Kintsugi-inspired design", "Solid brass base", "Heat-resistant coating", "Hand-polished finish"],
    dimensions: "Ø 90 × 45 cm",
    material: "Resin & Brass",
    finish: "High-Gloss Marbled",
    image: "/Gold-Veined Black Marble Table.png",
    theme: "Black Gold",
  },
  {
    id: "7",
    name: "BLACK CRYSTAL SINK WITH GOLD ACCENTS",
    category: "Basins",
    collection: "Private Collection",
    price: 195000,
    description: "A breathtaking black crystal sink accented with pure gold detailing.",
    features: ["Gold leaf accents", "Black crystal finish", "Smooth interior", "Hand-crafted"],
    dimensions: "Ø 45 × 15 cm",
    material: "Resin & Gold",
    finish: "High-Gloss",
    image: "/Black Crystal Sink with Gold Accents.png",
    theme: "Black Gold",
  },
  {
    id: "8",
    name: "CRYSTAL CHESS ON BLACK MARBLE",
    category: "Chess",
    collection: "Collector's Suite",
    price: 120000,
    description: "Clear and frosted crystal chess pieces arranged on a stark black marble board.",
    features: ["Crystal pieces", "Black marble base", "Tournament size", "Weighted"],
    dimensions: "60 × 60 × 8 cm",
    material: "Crystal & Marble",
    finish: "Polished",
    image: "/Crystal Chess on Black Marble.png",
    theme: "Black Premium",
  },
  {
    id: "9",
    name: "CRYSTAL SINK ON BLACK MARBLE",
    category: "Basins",
    collection: "Private Residence",
    price: 210000,
    description: "A translucent crystal sink that seems to float atop a heavy black marble vanity.",
    features: ["Translucent resin", "Black marble base", "Seamless drain", "Stain resistant"],
    dimensions: "Ø 45 × 15 cm",
    material: "Resin & Marble",
    finish: "Matte & Gloss",
    image: "/Crystal Sink on Black Marble.png",
    theme: "Black Premium",
  },
  {
    id: "10",
    name: "EMERALD CRYSTAL BASIN ON MARBLE VANITY",
    category: "Basins",
    collection: "Private Collection",
    price: 240000,
    description: "Vibrant emerald green basin featuring a jagged, natural crystalline exterior.",
    features: ["Emerald hue", "Raw crystal texture", "Polished interior", "Gold fixtures"],
    dimensions: "Ø 45 × 15 cm",
    material: "Premium Resin",
    finish: "Faceted",
    image: "/Emerald Crystal Basin on Marble Vanity.png",
    theme: "Green",
  },
  {
    id: "11",
    name: "EMERALD GEODE CRYSTAL CLOCK",
    category: "Wall Art",
    collection: "Collector's Suite",
    price: 175000,
    description: "A wall clock crafted to look like a freshly split emerald geode.",
    features: ["Geode design", "Gold hands", "Silent movement", "Resin crystals"],
    dimensions: "80 × 60 × 7 cm",
    material: "Resin & Gold",
    finish: "Textured",
    image: "/Emerald Geode Crystal Clock.png",
    theme: "Green",
  },
  {
    id: "12",
    name: "FACETED BLACK CRYSTAL CLOCK ON MARBLE",
    category: "Wall Art",
    collection: "Private Residence",
    price: 160000,
    description: "A monolithic black crystal clock with sharp, striking facets.",
    features: ["Geometric facets", "Deep black hue", "Minimalist hands", "Wall mountable"],
    dimensions: "80 × 60 × 7 cm",
    material: "Premium Resin",
    finish: "High-Gloss",
    image: "/Faceted Black Crystal Clock on Marble.png",
    theme: "Black Premium",
  },
  {
    id: "13",
    name: "LUXE BLUE AND GOLD CRYSTAL CHESSBOARD",
    category: "Chess",
    collection: "Private Collection",
    price: 185000,
    description: "Sapphire blue resin and gold leaf combine in this masterpiece of strategic design.",
    features: ["Sapphire blue", "Gold leaf inclusions", "Faceted edges", "Felted bases"],
    dimensions: "60 × 60 × 8 cm",
    material: "Resin & Gold Leaf",
    finish: "Polished",
    image: "/Luxe Blue and Gold Crystal Chessboard.png",
  },
  {
    id: "15",
    name: "OPULENT BLACK AND GOLD CHESSBOARD",
    category: "Chess",
    collection: "Private Collection",
    price: 165000,
    description: "An incredibly rich black resin board shattered with gold leaf veins.",
    features: ["Kintsugi style", "Heavy pieces", "Gold accents", "Display worthy"],
    dimensions: "60 × 60 × 8 cm",
    material: "Resin & Gold Leaf",
    finish: "High-Gloss",
    image: "/Opulent Black and Gold Chessboard.png",
    theme: "Black Gold",
  },
  {
    id: "16",
    name: "OPULENT BLUE AND GOLD MARBLE COFFEE TABLE",
    category: "Tables",
    collection: "Private Residence",
    price: 295000,
    description: "Deep oceanic blue marble with striking rivers of gold running through the surface.",
    features: ["Blue marble", "Gold rivers", "Brass frame", "Centerpiece design"],
    dimensions: "120 × 80 × 45 cm",
    material: "Marble & Brass",
    finish: "Polished",
    image: "/Opulent Blue and Gold Marble Coffee Table.png",
    theme: "Blue Gold",
  },
  {
    id: "17",
    name: "REGAL CRYSTAL GEODE CLOCK",
    category: "Wall Art",
    collection: "Collector's Suite",
    price: 190000,
    description: "A magnificent geode clock featuring deep crimson and white crystalline structures.",
    features: ["Crimson crystals", "White resin edge", "Gold detailing", "Silent sweep"],
    dimensions: "80 × 60 × 7 cm",
    material: "Resin",
    finish: "Textured",
    image: "/Regal Crystal Geode Clock.png",
    theme: "Red White",
  },
  {
    id: "18",
    name: "ROSE CRYSTAL GEODE CLOCK",
    category: "Wall Art",
    collection: "Private Residence",
    price: 170000,
    description: "Soft rose quartz inspired crystals form the body of this elegant timepiece.",
    features: ["Rose hue", "Organic shape", "Gold hands", "Wall mounted"],
    dimensions: "80 × 60 × 7 cm",
    material: "Premium Resin",
    finish: "Faceted",
    image: "/Rose Crystal Geode Clock.png",
    theme: "Pink White",
  },
  {
    id: "19",
    name: "ROSE QUARTZ AND IVORY CHESS ELEGANCE",
    category: "Chess",
    collection: "Private Collection",
    price: 145000,
    description: "A delicate and romantic chess set rendered in soft pink and creamy ivory resin.",
    features: ["Rose quartz style", "Ivory white squares", "Classic pieces", "Felted"],
    dimensions: "60 × 60 × 8 cm",
    material: "Resin",
    finish: "Matte",
    image: "/Rose Quartz and Ivory Chess Elegance.png",
    theme: "Pink White",
  }
];
